//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SugarMonkey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderedItems = new HashSet<OrderedItem>();
        }
    
        public int OrderID { get; set; }
        public int UserID { get; set; }
        public decimal GrossAmount { get; set; }
        public decimal TotalDiscounts { get; set; }
        public decimal SalesTax { get; set; }
        public decimal NetAmount { get; set; }
        public decimal PurchaseDate { get; set; }
        public int TrackingNumber { get; set; }
        public int AddressID { get; set; }
        public int DeliveryOptionID { get; set; }
        public string SpecialInstructions { get; set; }
        public System.DateTime OrderedDate { get; set; }
        public int OrderStageID { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual DeliveryOption DeliveryOption { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderedItem> OrderedItems { get; set; }
        public virtual OrderStage OrderStage { get; set; }
        public virtual User User { get; set; }
    }
}
